version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      - PINECONE_API_KEY=${PINECONE_API_KEY:-your_pinecone_api_key_here}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT:-your_pinecone_environment_here}
    restart: unless-stopped

  # Uncomment to use Pinecone emulator for local development
  # pinecone-emulator:
  #   image: pinecone/pinecone-emulator:latest
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - pinecone-data:/data
  #   environment:
  #     - PINECONE_HOST=0.0.0.0
  #     - PINECONE_PORT=8080

# volumes:
#   pinecone-data:
